### ISSUE TITLE
Hangs on partial result listener

### ISSUE THREAD

**Issue by vigneshpushkaran** [evancohen/sonus#92] opened 2019-01-04 07:05 UTC
Hi,

  The **Sonus** libarary works good but when I run for long time it gets hang on partial result event, then  again If I say **WAKEWORD** it started to work good, but issue(hangs on partial result) is coming again after some more time. Would this be internet issue?
If so How could I handle the issue.
Thanks in Advance.

**Comment by evancohen** [comment] 2019-03-08 20:34
What OS and device are you using? I just pushed a fix in [`🏷 1.0.1`](https://github.com/evancohen/sonus/releases/tag/1.0.1) that solved a hanging problem (although not specifically during partial results). Can you try the new version and see if you can get the issue to reproduce?

**Comment by evancohen** [comment] 2019-03-19 06:16
Closing this because I haven't gotten a response. I'm assuming this is fixed in the most recent version.

**Closed** 2019-03-19 16:49 UTC
