### ISSUE TITLE
Continue recognitionStream ?

### ISSUE THREAD

**Issue by buildog** [evancohen/sonus#19] opened 2016-11-18 20:23 UTC
Great implementation, very instructive :-)

I'm wondering what would be the best implementation to keep speech recognition after a first hotword, which is mostly the case on a conversationnal boot, user won't say everytime the hotword, dosen't make sense.

The problem there is that sonus  trigger the intent processing after the `final-result` emitted at the end of recognitionStream, so we need a way to manualy trigger the hotword in order to avoid a painfull UX.

Maybe a `const detector` > `sonus.detector` ?

**Comment by evancohen** [comment] 2016-11-19 02:08
Dupe of #18

**Closed by evancohen** 2016-11-19 02:08 UTC
